sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t andriybalashov/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andriybalashov/complex-test npm test

after_success:
  - docker build -t andriybalashov/multi-client ./client
  - docker build -t andriybalashov/multi-nginx ./nginx
  - docker build -t andriybalashov/multi-server ./server
  - docker build -t andriybalashov/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andriybalashov/multi-client
  - docker push andriybalashov/multi-nginx
  - docker push andriybalashov/multi-server
  - docker push andriybalashov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "complex"
  env: "Complex-env"
  bucket: "elasticbeanstalk-us-east-1-353294389480"
  bucket_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


